# Generated by Django 2.0.6 on 2018-09-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('businessentityid', models.IntegerField(db_column='BusinessEntityID', primary_key=True, serialize=False)),
                ('persontype', models.CharField(db_column='PersonType', max_length=2)),
                ('namestyle', models.BooleanField(db_column='NameStyle')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=8, null=True)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=50, null=True)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('suffix', models.CharField(blank=True, db_column='Suffix', max_length=10, null=True)),
                ('emailpromotion', models.IntegerField(db_column='EmailPromotion')),
                ('additionalcontactinfo', models.TextField(blank=True, db_column='AdditionalContactInfo', null=True)),
                ('demographics', models.TextField(blank=True, db_column='Demographics', null=True)),
                ('rowguid', models.CharField(max_length=36)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': '[AdventureWorks2014].[Person].[Person]',
                'managed': False,
            },
        ),
    ]
